describe('Verfy product women add to cart functionality', () => {
  it('Falid Add a detail product women Hoodies & Sweatshirts to cart', () => {
    cy.visit('https://magento.softwaretestingboard.com/customer/account/login/referer/aHR0cHM6Ly9tYWdlbnRvLnNvZnR3YXJldGVzdGluZ2JvYXJkLmNvbS8%2C/')
    cy.get('#email').type('halotester1@mail.com')
    cy.get('#pass').type('Halo12345$')
    cy.get('#send2').click()
    cy.get('[aria-label="store logo"]').should('be.visible')
    cy.get('[data-ui-id="page-title-wrapper"]').should('have.text', 'Home Page')
    cy.get('#ui-id-4').click()
    cy.get('.base').should('have.text', 'Women')
    cy.get('.categories-menu > :nth-child(2) > :nth-child(1) > a').click()
    cy.get('.base').should('have.text', 'Hoodies & Sweatshirts')
    cy.get('.wrapper > .products > :nth-child(1)').click()
    cy.get('#option-label-size-143-item-166').click()
    cy.get('.size > .swatch-attribute-selected-option').should('have.text', 'XS')
    cy.get('#product-addtocart-button').click()
    cy.get('[id="super_attribute[93]-error"]').should('have.text', 'This is a required field.')
  })
  it('success Add a detail product women Hoodies & Sweatshirts to cart', () => {
      cy.visit('https://magento.softwaretestingboard.com/customer/account/login/referer/aHR0cHM6Ly9tYWdlbnRvLnNvZnR3YXJldGVzdGluZ2JvYXJkLmNvbS8%2C/')
      cy.get('#email').type('halotester1@mail.com')
      cy.get('#pass').type('Halo12345$')
      cy.get('#send2').click()
      cy.get('[aria-label="store logo"]').should('be.visible')
      cy.get('[data-ui-id="page-title-wrapper"]').should('have.text', 'Home Page')
      cy.get('#ui-id-4').click()
      cy.get('.base').should('have.text', 'Women')
      cy.get('.categories-menu > :nth-child(2) > :nth-child(1) > a').click()
      cy.get('.base').should('have.text', 'Hoodies & Sweatshirts')
      cy.get('.wrapper > .products > :nth-child(1)').click()
      cy.get('#option-label-size-143-item-166').click()
      cy.get('.size > .swatch-attribute-selected-option').should('have.text', 'XS')
      cy.get('#option-label-color-93-item-52').click()
      cy.get('.swatch-attribute.color > .swatch-attribute-selected-option').should('have.text', 'Gray')
      cy.get('#qty').type('1')
      cy.get('#product-addtocart-button').click()
      cy.get('.message-success').should('be.visible')
      cy.get('.counter-number').should('be.visible')
  })
  
})

      //cy.get('#ui-id-3').click()
      //cy.get('.categories-menu > :nth-child(2) > :nth-child(1) > a').click()
      //cy.get('.wrapper > .products > :nth-child(1)').click()